### ISSUE TITLE
Can't launch llfi-gui 

### ISSUE THREAD

**Issue by Andre4102** [DependableSystemsLab/LLFI#125]
I installed llfi with the python script but i can't open the gui from command line due to the following error.

/usr/lib/jvm/java-8-openjdk-amd64/bin/java -classpath /usr/lib/jvm/java-8-openjdk-amd64/./jre/lib/*:/usr/lib/jvm/java-8-openjdk-amd64/./jre/lib/ext/*:/path/to/llfisrc/./gui/application/lib/*:/path/to/llfi/bin/../gui/application/lib/*:/path/to/llfi/bin/../gui application.Main

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: <init>
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:288)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:337)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	... 5 more
Caused by: java.lang.NoSuchMethodError: <init>
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:107)
	at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:39)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:156)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:140)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:278)
	... 9 more
I saw a similar problem here but there was no solution in there. I can't join the developer group because i can't find it anywhere.

**Comment by karthikp-ubc** [comment]
Sorry, the Java GUI isn't supported. Please use the CLI or Web GUI.
